### ISSUE TITLE
RESOLVED - Problem building main.styl when running npm start (or webpack-dev-server)

### ISSUE THREAD

**Issue by david-carroll** [HenrikJoreteg/hubtags.com#7]
Anyone else having issues building `main.styl` when using `webpack-dev-server` via `npm start`?

Everything else works fine when building the project using `webpack` via `npm run build`.  

See the error in the terminal output below when running `npm start`:

```
  [396] ./src/models/label.js 2.72 kB {0} [built]
  [397] ./src/helpers/github-xhr.js 2 kB {0} [built]
  [398] ./src/styles/main.styl 1.19 kB {0} [built] [1 error]
  [400] ./~/style-loader/addStyles.js 6.09 kB {0} [built]
  [401] ./~/octicons/octicons/octicons.css 972 bytes {0} [built]
  [402] ./~/css-loader!./~/postcss-loader!./~/octicons/octicons/octicons.css 11.9 kB {0} [built]
  [403] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
  [404] ./~/octicons/octicons/octicons.eot 82 bytes {0} [built]
  [405] ./~/octicons/octicons/octicons.woff 83 bytes {0} [built]
  [406] ./~/octicons/octicons/octicons.ttf 82 bytes {0} [built]
  [407] ./~/octicons/octicons/octicons.svg 82 bytes {0} [built]

ERROR in ./~/css-loader!./~/postcss-loader!./~/stylus-loader!./src/styles/main.styl
Module build failed: TypeError: /Assets/src/sandbox/hubtags.com/src/styles/main.styl:25:1
   21|   margin-top: 20px
   22|   > *
   23|     margin-left: 10px
   24|     margin-right: 10px
   25| 
-------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1429:5)
    at new SourceMapper (/Assets/src/sandbox/hubtags.com/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/Assets/src/sandbox/hubtags.com/node_modules/stylus/lib/renderer.js:94:9)
    at /Assets/src/sandbox/hubtags.com/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/Assets/src/sandbox/hubtags.com/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Assets/src/sandbox/hubtags.com/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Assets/src/sandbox/hubtags.com/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Assets/src/sandbox/hubtags.com/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Assets/src/sandbox/hubtags.com/node_modules/when/lib/Scheduler.js:62:19)
 @ ./src/styles/main.styl 4:14-168 13:2-17:4 14:20-174
webpack: bundle is now VALID.
```

The issue appears to be in the stylus library.  I'll keep troubleshooting this myself and let you know if I discover anything worth sharing.

**Comment by david-carroll** [comment]
The issue appears to occur in the stylus module when attempting to bundle with source-maps.

That is the reason this issue only occurs with `webpack-dev-server`.  The same error appears when I attempt to bundle with source-maps while running `webpack`.

The error is thrown in `hubtags.com/node_modules/stylus/lib/visitor/sourcemapper.js` on line 41:

```
if (extname(this.dest) === '.css') {  // <- Line 41
```

The reason is `this.dest` is `null` when it is passed into `extname(this.dest)`.  A simple fix would be to first check that `this.dest` isn't null:

```
if (this.dest && extname(this.dest) === '.css') {  // <- Line 41
```

**Comment by david-carroll** [comment]
As I was preparing to submit a pull request with this fix to the [stylus](https://github.com/stylus/stylus) repo, I discovered the change was [already merged](https://github.com/stylus/stylus/commit/c26e6d84fa35a90fb6b39981a67e974b5d6af703#diff-c86b72660975521fdda23b8978457619) into master about a month ago.  

For some reason, running `npm install` on this project pulled down an older version ([0.52.4](https://github.com/stylus/stylus/tree/0.52.4)) instead of the latest version [0.54.5](https://github.com/stylus/stylus/tree/0.54.5).  Version [0.52.4](https://github.com/stylus/stylus/tree/0.52.4) was committed in Sept 2015 about 8 versions ago.

I was able to resolve this by adding `"stylus": "^0.54.5"` to the hubtags.com package.json file, deleting my `node_modules` folder, and running `npm install`.  This pulled down the latest version of stylus and all is working now.

I hope this helps anyone else with this same issue.
